### PR TITLE
Create FakeSftpServerExtension.java

### PR DESCRIPTION
**Pull request by jsamsa**
Added Junit5 Extension (Rules are no longer supported).

### CODE REVIEW

**Comment by jsamsa** [comment]
Not sure why CI is failing, might be related to the build (somehow) pulling in apache sshd-core 2.0.0-SNAPSHOT. Build for me works, but it's using sshd-core 1.7.0.

**Comment by stefanbirkner** [comment]
Thanks for the PR. I'm planning to start work on a JUnit Lambda extension when fake-sftp-server-lambda is released.

**Comment by stefanbirkner** [comment]
I created a new library [Fake SFTP Server Lambda](https://github.com/stefanbirkner/fake-sftp-server-lambda) that is independent of the testing framework. You can use it with JUnit Lambda (JUnit 5).

**Comment by jsamsa** [comment]
Thank you

**Pull request closed without merging**
